DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS books_genres;
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
 id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
 name VARCHAR(255) NOT NULL,
 lastname VARCHAR(255) NOT NULL,
 email VARCHAR(255) NOT NULL,
 surname VARCHAR(255) NOT NULL,
 birthday DATETIME NOT NULL
);

CREATE TABLE books (
id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
description VARCHAR(255) NOT NULL,
views BIGINT DEFAULT 0,
author_id BIGINT NOT NULL,
FOREIGN KEY (author_id) REFERENCES users (id)
);

CREATE TABLE books_genres (
    book_id BIGINT NOT NULL,
    genre VARCHAR(255) NOT NULL,
    CONSTRAINT books_genres_idx UNIQUE (book_id, genre),
    FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE CASCADE
);

CREATE TABLE comments (
id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
text VARCHAR(500) NOT NULL,
author_id BIGINT,
book_id BIGINT NOT NULL,
createDate DATETIME NOT NULL default CURRENT_TIMESTAMP,
FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE SET NULL,
FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE CASCADE
);
