DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS books;

DROP TABLE IF EXISTS comments;

CREATE TABLE users (
 id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
 name VARCHAR(255) NOT NULL,
 lastname VARCHAR(255) NOT NULL,
 email VARCHAR(255) NOT NULL,
 surname VARCHAR(255) NOT NULL,
 birthday DATETIME NOT NULL
);

CREATE TABLE books (
id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
description VARCHAR(255) NOT NULL,
genres VARBINARY(255) NOT NULL,
author BIGINT NOT NULL,
views BIGINT DEFAULT 0
);

CREATE TABLE comments (
id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
text VARCHAR(500) NOT NULL,
author BIGINT,
book BIGINT NOT NULL
);
