#redis
spring.data.redis.port=6379
spring.data.redis.host=localhost
#redis
spring.data.redis.timeout=60000
#kafka
spring.kafka.bootstrap-servers=localhost:9092
#kafka:9093
#batch
spring.batch.jdbc.initialize-schema=always
#profile settings
spring.profiles.default=jdbc